apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    project: expense
    module: frontend
    env: dev
  ports:
  - name: frontend-port
    protocol: TCP
    port: 80 #service port
    targetPort: 80  #container port(app port)