apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::240939827212:role/eksctl-expense3-nodegroup-dev-NodeInstanceRole-plESS21FTMN5
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - pod-reader
      userarn: arn:aws:iam::240939827212:user/suresh
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2026-07-14T10:48:00Z"
  name: aws-auth
  namespace: kube-system
  # resourceVersion: "1311"
  uid: fca14c9c-cbc9-45df-8882-c2b030574540
