# apiVersion: eksctl.io/v1alpha5
# kind: ClusterConfig
# metadata:
#   name: expense
#   region: us-east-1
# managedNodeGroups:
#   - name: dev
#     instanceType: m5.large
#     desiredCapacity: 3
#     spot: true
#     # privateNetworking: false
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: expense3
  region: us-east-1
managedNodeGroups:
  - name: dev
    instanceType: t3.small
    desiredCapacity: 2
    # Remove the line below
    spot: true