apiVersion: v1
kind: ConfigMap
metadata: 
    name: backend
    namespace: expense
data:
  DB_HOST: mysql  #this is service name of mysql deployment file
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      module: backend
      env: dev
  template:
    metadata:
      labels:
        project: expense
        module: backend
        env: dev
    spec:
      containers:
      - name: backend
        image: kdprasad028/backend_july:v1  #try to chnage version of image and apply. it won't create bew verisons
        envFrom:
        - configMapRef:
            name: backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    project: expense
    module: backend
    env: dev
  ports:
  - name: backend-port
    protocol: TCP
    port: 8080 #service port
    targetPort: 8080  #container port(app port)