apiVersion: v1
kind: Secret
metadata:
  name: app-db-credentials
type: Opaque
stringData:
  username: "cHJhc2FkSwo="
  password: "cGFzc3dvcmQxMjMK"
---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: backend-service-pod
# spec:
#   containers:
#   - name: backend-container
#     image: nginx
#     env:
#     - name: DATABASE_USER
#       valueFrom:
#         secretKeyRef:
#           name: app-db-credentials
#           key: username
#     - name: DATABASE_PASSWORD
#       valueFrom:
#         secretKeyRef:
#           name: app-db-credentials
#           key: password