apiVersion: v1
kind: Service
metadata:
  name: nginx-sr
spec:
  selector:
    project: expense
    app: nginx
    env: dev
  ports:
  - name: nginx-port
    protocol: TCP
    port: 80 #service port
    targetPort: 80  #container port(app port)