apiVersion: v1
kind: Service
metadata:
  name: np-nginx
spec:
  type: NodePort
  selector:
    project: expense
    module: backend
    env: dev
  ports:
  - name: nodeport
    protocol: TCP
    port: 80
    targetPort: 80