apiVersion: v1
kind: Pod
metadata:
  name: app-nginx
  labels:
    project: expense
    app: nginx
    env: dev
spec:
  containers:
  - name: nginx
    # image: nginx:1.14.2
    image: nginx:alpine
    ports:
    - containerPort: 80