apiVersion: v1
kind: Pod
metadata:
  name: limits
  labels:
    app: frontend
    project: robo
    envronment: prod
spec:
  containers:
  - name: nginx-lmt
    image: nginx
    resources:
      requests:
        cpu: 250m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 128Mi