apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      project: expense
      module: frontend
      env: dev
  template:
    metadata:
      labels:
        project: expense
        module: frontend
        env: dev
    spec:
      containers:
      - name: backend
        image: kdprasad028/frontend_july:{{ .Values.deployment.imageVersion }}  #try to chnage version of image and apply. it won't create bew verisons
        resources:
          requests:
            cpu: "100m"
            memory: 64Mi
          limits:
            cpu: "120m"
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    project: expense
    module: frontend
    env: dev
  ports:
  - name: frontend-port
    protocol: TCP
    port: 80 #service port
    targetPort: 80  #container port(app port)
---
#HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.cpuUtilization }}
  # - type: Resource
  #   resource:
  #     name: memory
  #     target:
  #       type: Utilization
  #       averageUtilization: 75
